### ISSUE TITLE
Public share goes back to Organization

### ISSUE THREAD

**Issue by cpedrezuela** [arcpy/update-hosted-feature-service#20]
Hi Kevin,

Noticed that when I am updating a FS on AGOL, From public it goes to Organization. my FS_SHARE parameters is share=True, everyone=True and Org=True. Could you let me know if this is because of the 10.5 upgrade of AGOL? tnx

**Comment by khibma** [comment]
No, an upgrade wont have caused any issues. I'll have to run the code and see.
Basically you're saying you want it to be shared to EVERYONE, but its only sharing to your ORG?

**Comment by cpedrezuela** [comment]
Hi Kevin, this issue of mine has been sorted. It was just the settings on our AGOL that I need to activate so that publisher roles can share to Public.
