### ISSUE TITLE
Finds service but returns error that it couldn't find service

### ISSUE THREAD

**Issue by caleband** [arcpy/update-hosted-feature-service#9]
This is my first time trying this out and I received the following error (I'm pretty confident I have edited the settings.ini file correctly and it seems strange that the script finds the service but then returns an error saying it can't find the service):

Starting Feature Service publish process
found Feature Service : bf59bb5980624fd58f6d514234e4da6f

Could not find a service to update. Check the service name in the settings.ini

Traceback (most recent call last):
  File "I:\GIS\UtilitySMO_Updater\Python\update.py", line 492, in <module>
    agol = AGOLHandler(inputUsername, inputPswd, serviceName, folderName, proxyDict)
  File "I:\GIS\UtilitySMO_Updater\Python\update.py", line 39, in __init__
    self.SDitemID = self.findItem("Service Definition")
  File "I:\GIS\UtilitySMO_Updater\Python\update.py", line 78, in findItem
    sys.exit()
SystemExit

**Comment by caleband** [comment]
A helpful ESRI tech figured it out for me. I had deleted the service definition file online and the script won't work without it...

**Comment by amitksinha** [comment]
how did you delete it online

**Comment by caleband** [comment]
I deleted it within AGOL by selecting the service definition and then the
delete button. I attached a screen shots, hopefully it comes through...
